const data = {
    products: [
      {
        _id: '1',
        name: 'Flower Print Dress',
        category: 'Dress',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Grey Dress',
        category: 'Casual',
        image: '/images/p2.jpg',
        price: 100,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Loose Tshirt',
        category: 'T-Shirt',
        image: '/images/p3.jpg',
        price: 220,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Purple Silk Dress',
        category: 'Party Dress',
        image: '/images/p4.jpg',
        price: 78,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Pink Party Dress',
        category: 'Dress',
        image: '/images/p5.jpg',
        price: 65,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Net Print Dress',
        category: 'Party Dress',
        image: '/images/p6.jpg',
        price: 139,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;